var num1 = prompt("Ingrese el primer número");
var num2 = prompt("Ingrese el segundo número");
document.write("La suma es: ");
document.write(parseInt(num1)+parseInt(num2));
document.write(" ");
document.write("La resta es: ");
document.write(parseInt(num1)-parseInt(num2));
document.write(" ");
document.write("La multiplicación es: ");
document.write(parseInt(num1)*parseInt(num2));
document.write(" ");
document.write("La división es: ");
document.write(parseInt(num1)/parseInt(num2));
document.write(" ");
document.write("El modulo es: ");
document.write(parseInt(num1)%parseInt(num2));
document.write(" ");